name: Bug Report
description: Template for a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["dromse/2"]
assignees:
  - dromse
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us, what happen and what expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Also tell us, how to reproduce a bug?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Version
      description: What version of Grind Manager are you running?
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian Version
      description: What version of Obsidian are you running?
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What platform are you seeing the problem on? (Can be multiple)
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - iOS
        - Android
    validations:
        required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (`Ctrl + Shift + I`)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: additional
    attributes:
      label: Additional questions
      options:
        - label: I want to work on this issue
